#common configuration shared between all applications
configserver:
    name: Docker Gateway Registry
    status: Connected to the Gateway Registry running in Docker

gateway:
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production

eureka:
    client:
        serviceUrl:
            defaultZone: http://admin:admin@registry:8761/eureka/
